package com.shopping.mapper;



import com.shopping.model.CartInfos;
import com.shopping.model.CartInfosExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface CartInfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract int countByExample(CartInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract int deleteByExample(CartInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract int insert(CartInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract int insertSelective(CartInfos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract List<CartInfos> selectByExample(CartInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract int updateByExampleSelective(@Param("record") CartInfos record, @Param("example") CartInfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_infos
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public abstract int updateByExample(@Param("record") CartInfos record, @Param("example") CartInfosExample example);
}