package com.shopping.mapper;

import com.shopping.model.ItemCategories;
import com.shopping.model.ItemCategoriesExample;
import com.shopping.model.ItemsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;
@Mapper
public interface ItemCategoriesMapper {
    @Select("select category_id categoryId,category_name categoryName from item_categories where category_name=#{categoryName}")
    ItemCategories selectByName(String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int countByExample(ItemCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int deleteByExample(ItemCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int insert(ItemCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int insertSelective(ItemCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     * @param example
     */
    List<ItemCategories> selectByExample(ItemCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    ItemCategories selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") ItemCategories record, @Param("example") ItemsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int updateByExample(@Param("record") ItemCategories record, @Param("example") ItemCategoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int updateByPrimaryKeySelective(ItemCategories record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_categories
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    int updateByPrimaryKey(ItemCategories record);
}