package com.shopping.mapper;

import com.shopping.model.OrdersDetails;
import com.shopping.model.OrdersDetailsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OrdersDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    int countByExample(OrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    int deleteByExample(OrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    int insert(OrdersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    int insertSelective(OrdersDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    List<OrdersDetails> selectByExample(@Param("orderId") String orderId, @Param("example") OrdersDetailsExample example);

    List<OrdersDetails> selectByOrderId(@Param("orderId") String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrdersDetails record, @Param("example") OrdersDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_details
     *
     * @mbggenerated Sat Jun 01 10:22:47 CST 2019
     */
    int updateByExample(@Param("record") OrdersDetails record, @Param("example") OrdersDetailsExample example);
}