package com.shopping.model;

public class CartInfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_infos.user_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_infos.item_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_infos.item_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_infos.item_edition
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String itemEdition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_infos.item_count
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer itemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_infos.item_price
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer itemPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_infos.user_id
     *
     * @return the value of cart_infos.user_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_infos.user_id
     *
     * @param userId the value for cart_infos.user_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_infos.item_id
     *
     * @return the value of cart_infos.item_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_infos.item_id
     *
     * @param itemId the value for cart_infos.item_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_infos.item_name
     *
     * @return the value of cart_infos.item_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_infos.item_name
     *
     * @param itemName the value for cart_infos.item_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_infos.item_edition
     *
     * @return the value of cart_infos.item_edition
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getItemEdition() {
        return itemEdition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_infos.item_edition
     *
     * @param itemEdition the value for cart_infos.item_edition
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemEdition(String itemEdition) {
        this.itemEdition = itemEdition == null ? null : itemEdition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_infos.item_count
     *
     * @return the value of cart_infos.item_count
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_infos.item_count
     *
     * @param itemCount the value for cart_infos.item_count
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_infos.item_price
     *
     * @return the value of cart_infos.item_price
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_infos.item_price
     *
     * @param itemPrice the value for cart_infos.item_price
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemPrice(Integer itemPrice) {
        this.itemPrice = itemPrice;
    }

    @Override
    public String toString() {
        return "CartInfos{" +
                "userId=" + userId +
                ", itemId=" + itemId +
                ", itemName='" + itemName + '\'' +
                ", itemEdition='" + itemEdition + '\'' +
                ", itemCount=" + itemCount +
                ", itemPrice=" + itemPrice +
                '}';
    }
}