package com.shopping.model;

public class Items {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_edition
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String itemEdition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_price
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Double itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_amount
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer itemAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_description
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String itemDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.item_img_uri
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String itemImgUri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items.category_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_id
     *
     * @return the value of items.item_id
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_id
     *
     * @param itemId the value for items.item_id
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_name
     *
     * @return the value of items.item_name
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_name
     *
     * @param itemName the value for items.item_name
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_edition
     *
     * @return the value of items.item_edition
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getItemEdition() {
        return itemEdition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_edition
     *
     * @param itemEdition the value for items.item_edition
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemEdition(String itemEdition) {
        this.itemEdition = itemEdition == null ? null : itemEdition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_price
     *
     * @return the value of items.item_price
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Double getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_price
     *
     * @param itemPrice the value for items.item_price
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_amount
     *
     * @return the value of items.item_amount
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getItemAmount() {
        return itemAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_amount
     *
     * @param itemAmount the value for items.item_amount
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemAmount(Integer itemAmount) {
        this.itemAmount = itemAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_description
     *
     * @return the value of items.item_description
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_description
     *
     * @param itemDescription the value for items.item_description
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription == null ? null : itemDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.item_img_uri
     *
     * @return the value of items.item_img_uri
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getItemImgUri() {
        return itemImgUri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.item_img_uri
     *
     * @param itemImgUri the value for items.item_img_uri
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setItemImgUri(String itemImgUri) {
        this.itemImgUri = itemImgUri == null ? null : itemImgUri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items.category_id
     *
     * @return the value of items.category_id
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items.category_id
     *
     * @param categoryId the value for items.category_id
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public String toString() {
        return "Items{" +
                "itemId=" + itemId +
                ", itemName='" + itemName + '\'' +
                ", itemEdition='" + itemEdition + '\'' +
                ", itemPrice=" + itemPrice +
                ", itemAmount=" + itemAmount +
                ", itemDescription='" + itemDescription + '\'' +
                ", itemImgUri='" + itemImgUri + '\'' +
                ", categoryId=" + categoryId +
                '}';
    }
}