package com.shopping.model;

public class ItemCategories {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_categories.category_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_categories.category_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_categories.category_id
     *
     * @return the value of item_categories.category_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_categories.category_id
     *
     * @param categoryId the value for item_categories.category_id
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_categories.category_name
     *
     * @return the value of item_categories.category_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_categories.category_name
     *
     * @param categoryName the value for item_categories.category_name
     *
     * @mbggenerated Sat May 25 16:39:52 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    @Override
    public String toString() {
        return "ItemCategories{" +
                "categoryId=" + categoryId +
                ", categoryName='" + categoryName + '\'' +
                '}';
    }
}