package com.shopping.model;

public class OrdersDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_details.order_id
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_details.item_id
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_details.item_name
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_details.item_price
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    private Double itemPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_details.item_count
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    private Integer itemCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_details.item_amount
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    private Double itemAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_details.order_id
     *
     * @return the value of orders_details.order_id
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_details.order_id
     *
     * @param orderId the value for orders_details.order_id
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_details.item_id
     *
     * @return the value of orders_details.item_id
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_details.item_id
     *
     * @param itemId the value for orders_details.item_id
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_details.item_name
     *
     * @return the value of orders_details.item_name
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_details.item_name
     *
     * @param itemName the value for orders_details.item_name
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_details.item_price
     *
     * @return the value of orders_details.item_price
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public Double getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_details.item_price
     *
     * @param itemPrice the value for orders_details.item_price
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_details.item_count
     *
     * @return the value of orders_details.item_count
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public Integer getItemCount() {
        return itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_details.item_count
     *
     * @param itemCount the value for orders_details.item_count
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_details.item_amount
     *
     * @return the value of orders_details.item_amount
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public Double getItemAmount() {
        return itemAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_details.item_amount
     *
     * @param itemAmount the value for orders_details.item_amount
     *
     * @mbggenerated Fri Jun 21 10:59:02 CST 2019
     */
    public void setItemAmount(Double itemAmount) {
        this.itemAmount = itemAmount;
    }

    @Override
    public String toString() {
        return "OrdersDetails{" +
                "orderId='" + orderId + '\'' +
                ", itemId=" + itemId +
                ", itemName='" + itemName + '\'' +
                ", itemPrice=" + itemPrice +
                ", itemCount=" + itemCount +
                ", itemAmount=" + itemAmount +
                '}';
    }
}